# Generated by Django 5.0.6 on 2024-06-25 01:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Distrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TipoUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('correo', models.EmailField(max_length=150, unique=True)),
                ('contrasena', models.CharField(max_length=255)),
                ('imagen_url', models.CharField(blank=True, max_length=255, null=True)),
                ('estado', models.CharField(max_length=45)),
                ('fh_creacion', models.DateTimeField(auto_now_add=True)),
                ('id_tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_usuarios.tipousuario')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45)),
                ('apellido_paterno', models.CharField(max_length=45)),
                ('apellido_materno', models.CharField(max_length=45)),
                ('sexo', models.CharField(max_length=1)),
                ('dni', models.CharField(max_length=8, unique=True)),
                ('celular', models.CharField(max_length=9, unique=True)),
                ('fecha_nacimiento', models.DateField()),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('calificacion_promedio', models.FloatField(default=0)),
                ('curriculo_url', models.CharField(blank=True, max_length=255, null=True)),
                ('fh_creacion', models.DateTimeField(auto_now_add=True)),
                ('id_distrito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_usuarios.distrito')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_usuarios.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45)),
                ('apellido_paterno', models.CharField(max_length=45)),
                ('apellido_materno', models.CharField(max_length=45)),
                ('sexo', models.CharField(max_length=1)),
                ('dni', models.CharField(max_length=8, unique=True)),
                ('celular', models.CharField(max_length=9, unique=True)),
                ('fecha_nacimiento', models.DateField()),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fh_creacion', models.DateTimeField(auto_now_add=True)),
                ('id_distrito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_usuarios.distrito')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_usuarios.usuario')),
            ],
        ),
    ]
