# Generated by Django 5.0.6 on 2024-06-25 01:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestion_servicios', '0001_initial'),
        ('gestion_usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calificacion', models.IntegerField()),
                ('comentario', models.TextField(blank=True, null=True)),
                ('fh_creacion', models.DateTimeField(auto_now_add=True)),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_usuarios.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleCalificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_calificacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_calificaciones.calificacion')),
                ('id_proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_usuarios.proveedor')),
                ('id_servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_servicios.servicio')),
            ],
            options={
                'unique_together': {('id_calificacion', 'id_servicio', 'id_proveedor')},
            },
        ),
    ]
