spring:
  datasource:
    url: jdbc:mysql://localhost:3306/encuentranos
    username: root
    password: 
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect

  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 406079063544-mp76rvbd06klo0d4nqaleao4oavpfhvs.apps.googleusercontent.com
            clientSecret: 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
            
server:
  port: 4000
  
