# Generated by Django 5.0.6 on 2024-06-25 01:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestion_usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fh_creacion', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(max_length=45)),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_usuarios.cliente')),
                ('id_proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_usuarios.proveedor')),
            ],
        ),
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.TextField()),
                ('fh_creacion', models.DateTimeField(auto_now_add=True)),
                ('id_chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_chats.chat')),
                ('id_emisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes_enviados', to='gestion_usuarios.usuario')),
                ('id_receptor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes_recibidos', to='gestion_usuarios.usuario')),
            ],
        ),
    ]
