# Generated by Django 5.0.6 on 2024-06-25 05:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestion_servicios', '0001_initial'),
        ('gestion_usuarios', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id_contrato', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.CharField(max_length=45)),
                ('precio_final', models.FloatField()),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('hi_servicio', models.TimeField()),
                ('hf_servicio', models.TimeField()),
                ('fh_creacion', models.DateTimeField(auto_now_add=True)),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_usuarios.cliente')),
            ],
            options={
                'db_table': 'contrato',
            },
        ),
        migrations.CreateModel(
            name='DetalleContrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_actual', models.FloatField(blank=True, null=True)),
                ('id_contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_contratos.contrato')),
                ('id_proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_usuarios.proveedor')),
                ('id_servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_servicios.servicio')),
            ],
            options={
                'db_table': 'detalle_contrato',
                'unique_together': {('id_contrato', 'id_servicio', 'id_proveedor')},
            },
        ),
    ]
