# Generated by Django 5.0.6 on 2024-05-10 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id_servicio', models.AutoField(db_column='id_servicio', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='nombre', max_length=60, unique=True)),
                ('descripcion', models.TextField(db_column='descripcion')),
            ],
            options={
                'db_table': 'servicio',
                'indexes': [models.Index(fields=['nombre'], name='servicio_nombre_9b1175_idx')],
            },
        ),
    ]
